name: Build Porsche Design System

on:
  push:
    tags:
      - "*"

jobs:
  check-release-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies and build Porsche Design System
        run: |
          pwd
          wget -q https://github.com/porsche-design-system/porsche-design-system/archive/refs/tags/components-react-v${{ github.ref_name }}.zip
          unzip -q components-react-v${{ github.ref_name }}.zip
          cd porsche-design-system-components-react-v${{ github.ref_name }}
          yarn install --frozen-lockfile
          yarn build:core-dependencies
          yarn build:components-prod
          yarn build:components-js-prod
          yarn build:components-react
