name: Build Porsche Design System

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build code
        uses: actions/checkout@v4

      - run: |
          pwd
          ls -al

      - name: Download Porsche Design System v${{ github.ref_name }}
        run: |
          wget -q https://github.com/porsche-design-system/porsche-design-system/archive/refs/tags/components-react-v${{ github.ref_name }}.zip
          unzip -q components-react-v${{ github.ref_name }}.zip
          mv porsche-design-system-components-react-v${{ github.ref_name }}/ porsche-design-system/

      - run: |
          pwd
          ls -al

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "porsche-design-system/yarn.lock"

      - name: Install dependencies and build Porsche Design System
        run: |
          pwd
          cd porsche-design-system/
          pwd
          ls -al
          yarn install --frozen-lockfile
          yarn build:core-dependencies
          yarn build:components-prod
          yarn build:components-js-prod
          yarn build:components-react
          ls -al packages/assets/cdn/
